💫 About Me:
Welcome to My GitHub Profile! 👨‍💻
Berthy Perez Lases | Rust Developer & Blockchain Engineer
Languages: English | Russian | Spanish | Portuguese

With over 7 years of experience in the crypto industry and a solid background in marketing and leadership, I specialize in developing secure and scalable blockchain solutions. My career includes roles such as Rust Software Engineer, Chief Marketing Officer, and Project Lead, blending technical expertise with strategic business insights.

🔭 Currently Developing: A custom Rust-based blockchain protocol with a focus on cross-chain interoperability and DeFi applications.
🌐 Previous Roles: Rust Developer at Neural Nexus Global, Chief Content Officer at Crezu, and Project Strategist for a DeFi stealth mode startup.
🌱 Current Focus: ZK-SNARKs, Multi-Party Computation (MPC), and cryptographic resilience against quantum computing.
🎯 Background: Expertise in blockchain development, smart contract security, cryptography, and DeFi, along with 7+ years in digital marketing and content strategy.
🌐 Socials:


💻 Tech Stack:




📊 GitHub Stats:




✍️ Random Dev Quote:





