# 💫 About Me

## Welcome to My GitHub Profile! 👨‍💻  
### **Berthy Perez Lases | Rust Developer & Blockchain Engineer**  
**Languages:** English | Russian | Spanish | Portuguese  

With **over 7 years of experience** in the crypto industry and a solid background in **marketing** and **leadership**, I specialize in developing secure and scalable **blockchain solutions**. My career includes roles such as **Rust Software Engineer**, **Chief Marketing Officer**, and **Project Lead**, blending technical expertise with strategic business insights.

- 🔭 **Currently Developing:** A custom Rust-based blockchain protocol with a focus on cross-chain interoperability and DeFi applications.
- 🌐 **Previous Roles:** Rust Developer at Neural Nexus Global, Chief Content Officer at Crezu, and Project Strategist for a DeFi stealth mode startup.
- 🌱 **Current Focus:** ZK-SNARKs, Multi-Party Computation (MPC), and cryptographic resilience against quantum computing.
- 🎯 **Background:** Expertise in blockchain development, smart contract security, cryptography, and DeFi, along with 7+ years in digital marketing and content strategy.

---

## 🌐 Socials:
[![Instagram](https://img.shields.io/badge/Instagram-%23E4405F.svg?logo=Instagram&logoColor=white)](https://instagram.com/@berthyprzl)

---

# 💻 Tech Stack:

![Rust](https://img.shields.io/badge/rust-%23000000.svg?style=for-the-badge&logo=rust&logoColor=white) ![Go](https://img.shields.io/badge/go-%2300ADD8.svg?style=for-the-badge&logo=go&logoColor=white) ![Solidity](https://img.shields.io/badge/Solidity-%23363636.svg?style=for-the-badge&logo=solidity&logoColor=white) ![TypeScript](https://img.shields.io/badge/typescript-%23007ACC.svg?style=for-the-badge&logo=typescript&logoColor=white)  
![AWS](https://img.shields.io/badge/AWS-%23FF9900.svg?style=for-the-badge&logo=amazon-aws&logoColor=white) ![React](https://img.shields.io/badge/react-%2320232a.svg?style=for-the-badge&logo=react&logoColor=%2361DAFB) ![Web3.js](https://img.shields.io/badge/web3.js-F16822?style=for-the-badge&logo=web3.js&logoColor=white)  
![GitHub](https://img.shields.io/badge/github-%23121011.svg?style=for-the-badge&logo=github&logoColor=white) ![Kubernetes](https://img.shields.io/badge/kubernetes-%23326ce5.svg?style=for-the-badge&logo=kubernetes&logoColor=white)

---

# 📊 GitHub Stats:
![](https://github-readme-stats.vercel.app/api?username=squally-hotness&theme=dark&hide_border=false&include_all_commits=true&count_private=true)  
![](https://github-readme-streak-stats.herokuapp.com/?user=squally-hotness&theme=dark&hide_border=false)  
![](https://github-readme-stats.vercel.app/api/top-langs/?username=squally-hotness&theme=dark&hide_border=false&include_all_commits=true&count_private=true&layout=compact)

---

### ✍️ Random Dev Quote:
![](https://quotes-github-readme.vercel.app/api?type=horizontal&theme=radical)

[![](https://visitcount.itsvg.in/api?id=squally-hotness&icon=0&color=0)](https://visitcount.itsvg.in)

---
